import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Header } from "@/features/common/components/atoms/Header";
import { SidebarProvider, SidebarTrigger } from "@/shadcn/components/ui/sidebar";
import { AppSidebar } from "@/features/common/components/atoms/sidebar";
import { SidebarInset } from "@/shadcn/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <SidebarProvider defaultOpen={false}>
          <AppSidebar />
          <SidebarInset>
           <Header />
             <div className="flex-1 flex flex-col h-full">
               {children}
             </div>
          </SidebarInset>
       </SidebarProvider>
      </body>
    </html>
  )
}
